#!/bin/bash
#
# This script toggles the extended monitor outputs if something is connected
#

# your primary monitor
if [[ $# < 1 ]]
then
  echo "I need to know which device is primary" 1>&2
  exit 1
fi
DEFAULT_OUTPUT="$1"

# outputs to toggle if connected
OUTPUTS=$(xrandr | grep -e "connected" | sed -e "s/^\([^ ]\+\).*/\1/")

# get info from xrandr
XRANDR=`xrandr`

EXECUTE=""

for CURRENT in $OUTPUTS
do
  if [[ $CURRENT != $DEFAULT_OUTPUT ]]
  then
    if [[ $XRANDR == *$CURRENT\ connected*  ]] # is connected
    then
      if [[ $XRANDR == *$CURRENT\ connected\ \(* ]] # is disabled
      then
        EXECUTE+="--output $CURRENT --auto --left-of $DEFAULT_OUTPUT "
      else
        EXECUTE+="--output $CURRENT --off "
      fi
    else # make sure disconnected outputs are off 
      EXECUTE+="--output $CURRENT --off "
    fi
  fi
done

xrandr --output $DEFAULT_OUTPUT --primary --auto $EXECUTE

$HOME/.config/openbox/background

openbox --reconfigure
